name: Build Release
on:
  release:
    types: [published]
  push:
    tags: ['*']
  workflow_dispatch:

env:
  ECR_REPO: 305587085711.dkr.ecr.us-west-2.amazonaws.com/0g-da-client

jobs:
  build_contracts_image:
    name: Build docker image of accel contracts
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 305587085711.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_ACCESS_KEY }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.ECR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push images
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  make_release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: [build_contracts_image]
    steps:
      - uses: actions/checkout@v4
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/changelog-builder.json
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/osp-cli
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') || contains(github.ref, 'pre') }}